version: '3.8'

services:
  # CLI service with interactive plotting
  sesame-cli:
    build: .
    volumes:
      - ./data:/app/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-sesame}
      - DISPLAY=:99
      - SKIP_DB_CONNECTION=true
      - JWT_SECRET=test_secret
    command: ["--analysis", "lca", "--defaults"]
    depends_on:
      - db

  # Web interface service
  sesame-web:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-sesame}
      - FLASK_APP=app
      - FLASK_ENV=development
      - SKIP_DB_CONNECTION=true
      - JWT_SECRET=test_secret
    command: ["flask", "run", "--host=0.0.0.0"]
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-sesame}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
